# Generated by Django 6.1.1 on 2026-09-11 07:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('state', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pricing_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], db_index=True, default='standard', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('effective_period', models.GeneratedField(db_persist=True, expression=models.Func(models.F('effective_from'), models.F('effective_until'), function='TSTZRANGE'), output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField())),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SchedulePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('type', models.CharField(choices=[('trek', 'Trek'), ('expedition', 'Expedition'), ('bike_roadtrip', 'Bike Roadtrip'), ('foreign_trip', 'Foreign Trip'), ('family_holidays', 'Family Holidays')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('extreme', 'Extreme')], max_length=20)),
                ('seasons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('monsoon', 'Monsoon'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20), blank=True, default=list)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('max_altitude_m', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
