# Generated by Django 6.1.1 on 2026-09-11 07:42
from django.contrib.postgres.operations import BtreeGistExtension
import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # For exclusion constraint: https://docs.djangoproject.com/en/6.1/ref/contrib/postgres/operations/#btreegistextension
        BtreeGistExtension(),

        migrations.AddField(
            model_name='destination',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destination',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricing',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricing',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_pricings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricing',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulepackage',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulepackage',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulepackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_packages', to='trips.package'),
        ),
        migrations.AddField(
            model_name='schedulepackage',
            name='trip_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_packages', to='bookings.tripschedule'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='schedule_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricings', to='trips.schedulepackage'),
        ),
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trips.destination'),
        ),
        migrations.AddField(
            model_name='trip',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='trips.trip'),
        ),
        migrations.AddIndex(
            model_name='schedulepackage',
            index=models.Index(fields=['trip_schedule', 'is_available'], name='schedule_package_available_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedulepackage',
            constraint=models.UniqueConstraint(fields=('trip_schedule', 'package'), name='unique_package_per_schedule'),
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['schedule_package', 'pricing_type', 'is_active'], name='pricing_sched_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['schedule_package', 'customer', 'effective_from'], name='pricing_schedule_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricing',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gt', models.F('effective_from')), _connector='OR'), name='pricing_effective_until_after_from'),
        ),
        migrations.AddConstraint(
            model_name='pricing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pricing_type', 'standard'), ('customer__isnull', True)), models.Q(('pricing_type', 'custom'), ('customer__isnull', False)), _connector='OR'), name='pricing_customer_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='pricing',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True), ('pricing_type', 'standard')), expressions=[('schedule_package', '='), ('effective_period', '&&')], name='pricing_standard_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='pricing',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True), ('pricing_type', 'custom')), expressions=[('schedule_package', '='), ('customer', '='), ('effective_period', '&&')], name='pricing_custom_no_overlap'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['type'], name='trip_type_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trip_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['difficulty'], name='trip_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['destination', 'status'], name='trip_destination_status_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['trip', 'is_active'], name='package_trip_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('trip', 'slug'), name='unique_package_slug_per_trip'),
        ),
    ]
