# Generated by Django 6.1.1 on 2026-09-11 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='trips.pricing'),
        ),
        migrations.AddField(
            model_name='bookingtraveler',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_travelers', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingtraveler',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtraveler',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveler',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveler',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveler',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traveler_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtraveler',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_travelers', to='bookings.traveler'),
        ),
        migrations.AddField(
            model_name='tripschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripschedule',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripschedule',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.tripschedule'),
        ),
        migrations.AddIndex(
            model_name='bookingtraveler',
            index=models.Index(fields=['booking'], name='booking_traveler_booking_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingtraveler',
            index=models.Index(fields=['traveler'], name='booking_traveler_traveler_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingtraveler',
            constraint=models.UniqueConstraint(fields=('booking', 'traveler'), name='unique_traveler_per_booking'),
        ),
        migrations.AddIndex(
            model_name='tripschedule',
            index=models.Index(fields=['trip', 'start_date'], name='trip_schedule_trip_start_idx'),
        ),
        migrations.AddIndex(
            model_name='tripschedule',
            index=models.Index(fields=['status', 'start_date'], name='trip_schedule_status_start_idx'),
        ),
    ]
