# Generated by Django 6.1.1 on 2026-09-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='capacity_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tripschedule',
            name='capacity',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
