# Generated by Django 6.1.1 on 2026-09-15 07:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_capacity_holds_waitlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trip_schedule', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_policy', to='bookings.tripschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CancellationPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('minimum_days_before_departure', models.PositiveIntegerField()),
                ('refund_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='bookings.cancellationpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('policy_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('policy_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('rule_min_days_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('refund_percentage_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('days_before_departure', models.IntegerField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='bookings.booking')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_cancellations', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_cancellations', to=settings.AUTH_USER_MODEL)),
                ('cancellation_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='bookings.cancellationpolicy')),
                ('cancellation_policy_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='bookings.cancellationpolicyrule')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank transfer'), ('CASH', 'Cash'), ('CARD', 'Card'), ('OTHER', 'Other')], max_length=20)),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual'), ('RAZORPAY', 'Razorpay')], default='MANUAL', max_length=20)),
                ('provider_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual'), ('RAZORPAY', 'Razorpay')], default='MANUAL', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='bookings.booking')),
                ('cancellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='bookings.cancellation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_refunds', to=settings.AUTH_USER_MODEL)),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_overrides', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='bookings.payment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cancellationpolicyrule',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_days_before_departure__gte', 0)), name='cancel_rule_days_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='cancellationpolicyrule',
            constraint=models.CheckConstraint(condition=models.Q(('refund_percentage__gte', Decimal('0.00')), ('refund_percentage__lte', Decimal('100.00'))), name='cancel_rule_refund_pct_valid'),
        ),
        migrations.AddConstraint(
            model_name='cancellationpolicyrule',
            constraint=models.UniqueConstraint(fields=('policy', 'minimum_days_before_departure'), name='unique_cancel_policy_threshold'),
        ),
        migrations.AddIndex(
            model_name='cancellation',
            index=models.Index(fields=['booking', 'status'], name='cancel_booking_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cancellation',
            index=models.Index(fields=['status', 'created'], name='cancel_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='cancellation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REQUESTED', 'APPROVED'])), fields=('booking',), name='unique_active_booking_cancellation'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'status'], name='payment_booking_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created'], name='payment_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='payment_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('paid_at__isnull', True), ('status__in', ['PAID', 'REFUNDED']), _connector='OR'), name='payment_paid_at_only_after_payment'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['PAID', 'REFUNDED']), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='payment_paid_status_requires_paid_at'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id__isnull', False)), fields=('provider', 'provider_transaction_id'), name='unique_payment_provider_transaction'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['booking', 'status'], name='refund_booking_status_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='refund_payment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='refund_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('calculated_amount__gte', Decimal('0.00'))), name='refund_calculated_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('approved_amount__gte', Decimal('0.00'))), name='refund_approved_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('approved_amount', models.F('calculated_amount')), models.Q(('override_reason__isnull', False), models.Q(('override_reason', ''), _negated=True), ('override_by__isnull', False)), _connector='OR'), name='refund_override_requires_reason_and_user'),
        ),
    ]
